const definitionsMap = {
  "name.firstName": ["firstname"],
  "name.lastName": ["lastname"],
  "name.findName": ["findname"],
  "name.jobTitle": ["jobtitle"],
  "name.prefix": ["nameprefix"],
  "name.suffix": ["namesuffix"],
  "name.title": ["nametitle"],
  "name.jobDescriptor": ["jobdescriptor"],
  "name.jobArea": ["jobarea"],
  "name.jobType": ["jobtype"],
  "address.zipCode": ["zipcode"],
  "address.city": ["city"],
  "address.cityPrefix": ["cityprefix"],
  "address.citySuffix": ["citysuffix"],
  "address.streetName": ["streetname"],
  "address.streetAddress": ["streetaddress"],
  "address.streetSuffix": ["streetsuffix"],
  "address.streetPrefix": ["streetprefix"],
  "address.secondaryAddress": ["secondaryaddress"],
  "address.county": ["county"],
  "address.country": ["country"],
  "address.countryCode": ["countrycode"],
  "address.state": ["state"],
  "address.stateAbbr": ["stateabbr"],
  "address.latitude": ["latitude"],
  "address.longitude": ["longitude"],
  "company.suffixes": ["suffixes"],
  "company.companyName": ["companyname"],
  "company.companySuffix": ["companysuffix"],
  "company.catchPhrase": ["catchphrase"],
  "company.bs": ["bs"],
  "company.catchPhraseAdjective": ["catchphraseadjective"],
  "company.catchPhraseDescriptor": ["catchphrasedescriptor"],
  "company.catchPhraseNoun": ["catchphrasenoun"],
  "company.bsAdjective": ["bsadjective"],
  "company.bsBuzz": ["bsbuzz"],
  "company.bsNoun": ["bsnoun"],
  "lorem.word": ["word"],
  "lorem.words": ["words"],
  "lorem.sentence": ["sentence"],
  "lorem.slug": ["slug"],
  "lorem.sentences": ["sentences"],
  "lorem.paragraph": ["paragraph"],
  "lorem.paragraphs": ["paragraphs"],
  "lorem.text": ["text"],
  "lorem.lines": ["lines"],
  "hacker.abbreviation": ["abbreviation"],
  "hacker.adjective": ["adjective"],
  "hacker.noun": ["noun"],
  "hacker.verb": ["verb"],
  "hacker.ingverb": ["ingverb"],
  "hacker.phrase": ["phrase"],
  "finance.account": ["account"],
  "finance.accountName": ["accountname"],
  "finance.mask": ["mask"],
  "finance.amount": ["amount"],
  "finance.transactionType": ["transactiontype"],
  "finance.currencyCode": ["currencycode"],
  "finance.currencyName": ["currencyname"],
  "finance.currencySymbol": ["currencysymbol"],
  "finance.bitcoinAddress": ["bitcoinaddress"],
  "finance.iban": ["iban"],
  "finance.bic": ["bic"],
  "internet.avatar": ["avatar"],
  "internet.email": ["email"],
  "internet.exampleEmail": ["exampleemail"],
  "internet.userName": ["username"],
  "internet.protocol": ["protocol"],
  "internet.url": ["url", "href"],
  "internet.domainName": ["domainname"],
  "internet.domainSuffix": ["domainsuffix"],
  "internet.domainWord": ["domainword"],
  "internet.ip": ["ip"],
  "internet.ipv6": ["ipv6"],
  "internet.userAgent": ["useragent"],
  "internet.color": ["color"],
  "internet.mac": ["mac"],
  "internet.password": ["password"],
  "commerce.color": ["color"],
  "commerce.department": ["department"],
  "commerce.productName": ["productname"],
  "commerce.price": ["price"],
  "commerce.productAdjective": ["productadjective"],
  "commerce.productMaterial": ["productmaterial"],
  "commerce.product": ["product"],
  "database.column": ["column"],
  "database.type": ["type"],
  "database.collation": ["collation"],
  "database.engine": ["engine"],
  "system.fileName": ["filename"],
  "system.commonFileName": ["commonfilename"],
  "system.mimeType": ["mimetype"],
  "system.commonFileType": ["commonfiletype"],
  "system.commonFileExt": ["commonfileext"],
  "system.fileType": ["filetype"],
  "system.fileExt": ["fileext"],
  "system.directoryPath": ["directorypath"],
  "system.filePath": ["filepath"],
  "system.semver": ["semver"],
  "date.past": ["past"],
  "date.future": ["future"],
  "date.between": ["between"],
  "date.recent": ["recent"],
  "date.month": ["month"],
  "date.weekday": ["weekday"],
  "random.number": ["number", "count"],
  "random.arrayElement": ["arrayelement"],
  "random.objectElement": ["objectelement"],
  "random.uuid": ["uuid", "guid", "uid"],
  "random.boolean": ["boolean", "is"],
  "random.word": ["word"],
  "random.words": ["words"],
  "random.image": ["image", "img", "thumb", "thumbnail"],
  "random.locale": ["locale"],
  "random.alphaNumeric": ["alphanumeric"]
};

module.exports = Object.keys(definitionsMap).reduce(
  (defArr, fakerFn) =>
    defArr.concat(
      definitionsMap[fakerFn].map(keyword => ({ keyword, fakerFn }))
    ),
  []
);
